version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[deps]"
    open-pull-requests-limit: 5

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[ci]"
    open-pull-requests-limit: 5
